export const ERROR_CODES = [
  "ERR_SESSION_CANCELLED",
  "ERR_SESSION_NOT_SCHEDULED",
  "ERR_ALREADY_CHECKED_IN_BY_OTHER",
  "ERR_SESSION_HAS_ATTENDANCE",
  "ERR_ATTENDANCE_EDIT_WINDOW_EXPIRED",
  "ERR_STUDENT_NOT_ENROLLED",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
