export const ERROR_CODES = [
  "ERR_SESSION_CANCELLED",
  "ERR_SESSION_NOT_SCHEDULED",
  "ERR_ALREADY_CHECKED_IN_BY_OTHER",
  "ERR_SESSION_HAS_ATTENDANCE",
  "ERR_ATTENDANCE_EDIT_WINDOW_EXPIRED",
  "ERR_STUDENT_NOT_ENROLLED",
  // CU32 — course progress / certification
  "ERR_COURSE_NODE_CERTIFIED",
  "ERR_COURSE_NODE_NOT_COMPLETE",
  "ERR_COURSE_NODE_HAS_CERTIFICATIONS",
  "ERR_COURSE_NODE_NOT_FOUND",
  "ERR_COURSE_STUDENT_OUT_OF_SCOPE",
  "ERR_COURSE_NOT_PUBLISHABLE",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
