/**
 * Load Panchang year data: bundled JSON + AsyncStorage cache, offline-first.
 */
import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  panchangYearSchema,
  type PanchangYear,
} from "@/lib/panchang/schema";
import { fetchRemotePanchangYear } from "@/lib/panchang/remote";
import {
  panchangCacheKey,
  pickNewerPanchangYear,
} from "@/lib/panchang/version";

function parseYear(raw: unknown): PanchangYear | null {
  const parsed = panchangYearSchema.safeParse(raw);
  return parsed.success ? parsed.data : null;
}

/**
 * Years shipped inside the app binary. Deliberately EMPTY.
 *
 * What used to be here was assets/data/panchang-2026.json, generated by
 * scripts/generate-panchang-2026.mjs — arithmetic tithi progression under a
 * header that said "Illustrative anchors — not astronomical truth". It placed
 * Samvatsari on Shravan Vad 14, three weeks before Bhadarvo Sud 4, and shipped
 * that to families deciding when to observe it. Both files are deleted.
 *
 * §17.6.1: a Panchang year is transcribed from a published Tapagachh Panchang
 * and verified by a named authority. Nothing else may appear here. To add one,
 * put the transcription in assets/data/, import it, and parse it through
 * parseYear — panchangYearSchema will reject it unless it carries provenance
 * naming who verified it, and panchangAnchorIssues checks it against the fixed
 * festivals before anyone publishes it.
 *
 * Until then the app fetches published years from the API (fetchRemotePanchangYear)
 * and shows an honest empty state when it has none.
 */
const BUNDLED: Record<number, PanchangYear> = {};

export function bundledPanchangYear(year: number): PanchangYear | null {
  return BUNDLED[year] ?? null;
}

export async function readCachedPanchangYear(
  year: number,
): Promise<PanchangYear | null> {
  try {
    const raw = await AsyncStorage.getItem(panchangCacheKey(year));
    if (!raw) return null;
    return parseYear(JSON.parse(raw));
  } catch {
    return null;
  }
}

export async function writeCachedPanchangYear(
  year: number,
  data: PanchangYear,
): Promise<void> {
  await AsyncStorage.setItem(panchangCacheKey(year), JSON.stringify(data));
}

/**
 * Offline-first load: max(cache, bundled), then best-effort remote (stub).
 */
export async function loadPanchangYear(year: number): Promise<PanchangYear | null> {
  const bundled = bundledPanchangYear(year);
  const cached = await readCachedPanchangYear(year);
  let current =
    bundled || cached
      ? pickNewerPanchangYear(cached, bundled ?? cached!)
      : null;

  // The remote year wins when its contentVersion is higher, and is persisted
  // so the next launch has it offline.
  try {
    const remote = await fetchRemotePanchangYear(year);
    if (remote) {
      const next = pickNewerPanchangYear(remote, current ?? remote);
      if (next === remote) {
        await writeCachedPanchangYear(year, remote);
      }
      current = next;
    }
  } catch {
    /* stay on local */
  }

  return current;
}

/** Asia/Kolkata "today" as YYYY-MM-DD. */
export function todayIstDate(): string {
  return new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" });
}

export function yearFromIsoDate(isoDate: string): number {
  return Number(isoDate.slice(0, 4));
}
