/**
 * Drizzle migration runner (SPEC §18.7).
 *
 *   1. Connect to Postgres via the write URL.
 *   2. Acquire `pg_advisory_lock(987654321)` so concurrent runs serialise.
 *   3. Run the drizzle migrator over `./migrations`.
 *   4. Release the lock in a `try / finally`.
 *
 * In Step 3 there are no migrations yet; the script exits 0 with "no
 * migrations found" once the empty `migrations/` directory is walked. Step 4
 * lands the actual schema migrations.
 *
 * Invoked via `pnpm --filter @jp/api db:migrate`.
 */

import fs from 'node:fs';
import path from 'node:path';

import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';

const ADVISORY_LOCK_KEY = 987_654_321;

async function main(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error('DATABASE_URL is required for migrations');
  }

  const ssl = (process.env.DATABASE_SSL ?? 'false').toLowerCase() === 'true';
  // Script is invoked via `pnpm --filter @jp/api db:migrate`, which sets cwd
  // to apps/api. Resolving from cwd keeps the path stable across both tsx
  // execution and tsc-compiled CJS output.
  const migrationsFolder = path.resolve(process.cwd(), 'src/db/migrations');

  // postgres.js with max=1 + prepare=false → one TCP connection, suitable for
  // both the advisory lock and the migrator (which serialises DDL anyway).
  const sql = postgres(url, {
    max: 1,
    ssl: ssl ? { rejectUnauthorized: true } : false,
    prepare: false,
    connection: { application_name: 'jp-api-migrate' },
  });
  const db = drizzle(sql);

  console.info(`[migrate] DB=${redactUrl(url)} migrationsFolder=${migrationsFolder}`);

  try {
    console.info(`[migrate] acquiring pg_advisory_lock(${ADVISORY_LOCK_KEY})…`);
    await sql`SELECT pg_advisory_lock(${ADVISORY_LOCK_KEY})`;

    try {
      // Drizzle requires meta/_journal.json even with zero migrations. It is
      // generated by `drizzle-kit generate`. Step 3 ships an empty schema, so
      // the file does not exist yet — exit cleanly in that case (Step 4 adds
      // the first migration and the journal).
      const journalPath = path.join(migrationsFolder, 'meta', '_journal.json');
      if (!fs.existsSync(journalPath)) {
        console.info(
          '[migrate] no migration journal found yet — nothing to apply (Step 4 will land the first migration)',
        );
      } else {
        await migrate(db, { migrationsFolder });

        console.info('[migrate] migrations applied successfully');
      }
    } finally {
      await sql`SELECT pg_advisory_unlock(${ADVISORY_LOCK_KEY})`;

      console.info('[migrate] advisory lock released');
    }
  } finally {
    await sql.end({ timeout: 5 });
  }
}

function redactUrl(u: string): string {
  // Strip the password from the connection string before logging.
  try {
    const parsed = new URL(u);
    if (parsed.password) parsed.password = '****';
    return parsed.toString();
  } catch {
    return '<unparseable-url>';
  }
}

main().catch((err) => {
  console.error('[migrate] FAILED', err);
  process.exit(1);
});
