/**
 * Shared API error codes. Prefer these over ad-hoc strings in fail().
 * Mirrors the intended @jp/shared/errors surface for this monorepo.
 */
export const ERROR_CODES = [
  "ERR_UNAUTHENTICATED",
  "ERR_TOKEN_INVALID",
  "ERR_USER_INACTIVE",
  "ERR_FORBIDDEN",
  "ERR_NOT_FOUND",
  "ERR_VALIDATION_FAILED",
  "ERR_CONFLICT",
  "ERR_SESSION_CANCELLED",
  "ERR_SESSION_NOT_SCHEDULED",
  "ERR_ALREADY_CHECKED_IN_BY_OTHER",
  "ERR_ATTENDANCE_EDIT_WINDOW_EXPIRED",
  "ERR_STUDENT_NOT_ENROLLED",
  "ERR_NIYAM_REVERSAL_WINDOW_EXPIRED",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const ErrorCode = {
  UNAUTHENTICATED: "ERR_UNAUTHENTICATED",
  TOKEN_INVALID: "ERR_TOKEN_INVALID",
  USER_INACTIVE: "ERR_USER_INACTIVE",
  FORBIDDEN: "ERR_FORBIDDEN",
  NOT_FOUND: "ERR_NOT_FOUND",
  VALIDATION_FAILED: "ERR_VALIDATION_FAILED",
  CONFLICT: "ERR_CONFLICT",
  SESSION_CANCELLED: "ERR_SESSION_CANCELLED",
  SESSION_NOT_SCHEDULED: "ERR_SESSION_NOT_SCHEDULED",
  ALREADY_CHECKED_IN_BY_OTHER: "ERR_ALREADY_CHECKED_IN_BY_OTHER",
  ATTENDANCE_EDIT_WINDOW_EXPIRED: "ERR_ATTENDANCE_EDIT_WINDOW_EXPIRED",
  STUDENT_NOT_ENROLLED: "ERR_STUDENT_NOT_ENROLLED",
  NIYAM_REVERSAL_WINDOW_EXPIRED: "ERR_NIYAM_REVERSAL_WINDOW_EXPIRED",
} as const satisfies Record<string, ErrorCode>;
