// notification-fanout.js — SPEC.md §15.6 / SLO #4
//
// 100 admin notice posts × 500 recipients = 50,000 in-flight pushes.
// We measure end-to-end delivery latency by polling
// `GET /v1/notifications?limit=1` per recipient and timing when the new
// notice id appears.
//
// SLO:
//   95% of recipient notifications visible within 30 seconds of post.
//
// Run:
//   K6_TOKENS_FILE=tokens.json k6 run \
//     --env BASE_URL=http://localhost:3000 \
//     --env CITY_ADMIN_TOKEN=$(jq -r '.[0].token' tokens.json) \
//     --env RECIPIENT_TOKENS_FILE=recipient-tokens.json \
//     infra/load-tests/k6/notification-fanout.js

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Counter, Rate } from 'k6/metrics';
import { SharedArray } from 'k6/data';

import { BASE_URL, headers, readyOrAbort } from './lib/auth.js';

const recipientTokens = new SharedArray('recipient-tokens', () => {
  const path = __ENV.RECIPIENT_TOKENS_FILE || './recipient-tokens.json';
  try {
    // eslint-disable-next-line no-restricted-globals
    return JSON.parse(open(path));
  } catch {
    return ['PLACEHOLDER'];
  }
});

export const options = {
  scenarios: {
    admin_post: {
      executor: 'per-vu-iterations',
      vus: 100,
      iterations: 1,
      maxDuration: '60s',
      exec: 'postNotice',
    },
    recipient_poll: {
      executor: 'per-vu-iterations',
      vus: Math.min(500, Math.max(1, recipientTokens.length || 1)),
      iterations: 1,
      maxDuration: '90s',
      exec: 'pollNotifications',
      startTime: '5s',
    },
  },
  thresholds: {
    delivered_within_30s: ['rate>0.95'],
    http_req_failed: ['rate<0.02'],
  },
};

const deliveredWithin30s = new Rate('delivered_within_30s');
const noticesPosted = new Counter('notices_posted');

export function setup() {
  readyOrAbort();
}

export function postNotice() {
  const token = __ENV.CITY_ADMIN_TOKEN || 'PLACEHOLDER';
  const body = JSON.stringify({
    title_en: `k6 load test notice ${__VU}-${Date.now()}`,
    title_hi: `लोड टेस्ट सूचना ${__VU}-${Date.now()}`,
    body_en: 'Synthetic notice generated by infra/load-tests/k6/notification-fanout.js',
    body_hi: 'सिंथेटिक सूचना',
    audience: 'city',
    is_critical: false,
  });
  const r = http.post(`${BASE_URL}/v1/notices`, body, {
    headers: headers(token),
    tags: { name: 'notice-create' },
  });
  noticesPosted.add(1);
  check(r, { 'notice 201': (res) => res.status === 201 });
}

export function pollNotifications() {
  const token =
    recipientTokens[__VU % recipientTokens.length].token ||
    recipientTokens[__VU % recipientTokens.length];
  const start = Date.now();
  const deadline = start + 30_000;
  let delivered = false;
  while (Date.now() < deadline && !delivered) {
    const r = http.get(`${BASE_URL}/v1/notifications?limit=1`, {
      headers: headers(token),
      tags: { name: 'notif-poll' },
    });
    if (r.status === 200 && r.body && r.body.includes('"created_at"')) {
      delivered = true;
      break;
    }
    sleep(2);
  }
  deliveredWithin30s.add(delivered);
}
