CREATE INDEX "idx_cities_state" ON "cities" USING btree ("state_id");--> statement-breakpoint
CREATE INDEX "idx_device_sessions_user" ON "device_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_otp_codes_phone" ON "otp_codes" USING btree ("phone");--> statement-breakpoint
CREATE INDEX "idx_users_city" ON "users" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_users_state" ON "users" USING btree ("state_id");--> statement-breakpoint
CREATE INDEX "idx_users_role" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_batches_centre" ON "batches" USING btree ("centre_id");--> statement-breakpoint
CREATE INDEX "idx_batches_shikshak" ON "batches" USING btree ("shikshak_id");--> statement-breakpoint
CREATE INDEX "idx_centre_holidays_centre" ON "centre_holidays" USING btree ("centre_id");--> statement-breakpoint
CREATE INDEX "idx_centres_city" ON "centres" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_centres_state" ON "centres" USING btree ("state_id");--> statement-breakpoint
CREATE INDEX "idx_sanchalak_centre_assignments_user" ON "sanchalak_centre_assignments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_sanchalak_centre_assignments_centre" ON "sanchalak_centre_assignments" USING btree ("centre_id");--> statement-breakpoint
CREATE INDEX "idx_shikshak_batch_assignments_user" ON "shikshak_batch_assignments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_shikshak_batch_assignments_batch" ON "shikshak_batch_assignments" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_enrolments_student" ON "enrolments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_enrolments_batch" ON "enrolments" USING btree ("requested_batch_id");--> statement-breakpoint
CREATE INDEX "idx_enrolments_centre" ON "enrolments" USING btree ("requested_centre_id");--> statement-breakpoint
CREATE INDEX "idx_msv_enrolments_student" ON "msv_enrolments" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_students_centre" ON "students" USING btree ("centre_id");--> statement-breakpoint
CREATE INDEX "idx_students_user" ON "students" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_students_parent" ON "students" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "idx_students_batch" ON "students" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_attendance_student" ON "attendance" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_attendance_session" ON "attendance" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_session_cancellations_session" ON "session_cancellations" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_batch" ON "sessions" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_punya_transactions_student" ON "punya_transactions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_punya_transactions_student_created" ON "punya_transactions" USING btree ("student_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_niyam_streaks_student" ON "niyam_streaks" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_niyam_streaks_niyam" ON "niyam_streaks" USING btree ("niyam_id");--> statement-breakpoint
CREATE INDEX "idx_niyam_submissions_student" ON "niyam_submissions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_niyam_submissions_niyam" ON "niyam_submissions" USING btree ("niyam_id");--> statement-breakpoint
CREATE INDEX "idx_notice_reads_notice" ON "notice_reads" USING btree ("notice_id");--> statement-breakpoint
CREATE INDEX "idx_notice_reads_user" ON "notice_reads" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_notices_centre" ON "notices" USING btree ("centre_id");--> statement-breakpoint
CREATE INDEX "idx_notices_city" ON "notices" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_notices_state" ON "notices" USING btree ("state_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_attendance_scans_session" ON "shivir_attendance_scans" USING btree ("shivir_session_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_attendance_scans_student" ON "shivir_attendance_scans" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_events_city" ON "shivir_events" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_events_state" ON "shivir_events" USING btree ("state_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_registrations_shivir" ON "shivir_registrations" USING btree ("shivir_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_registrations_student" ON "shivir_registrations" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_sessions_shivir" ON "shivir_sessions" USING btree ("shivir_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_volunteers_shivir" ON "shivir_volunteers" USING btree ("shivir_id");--> statement-breakpoint
CREATE INDEX "idx_shivir_volunteers_user" ON "shivir_volunteers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_library_access_logs_item" ON "library_access_logs" USING btree ("library_item_id");--> statement-breakpoint
CREATE INDEX "idx_library_access_logs_user" ON "library_access_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_gallery_items_student" ON "gallery_items" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_gallery_items_niyam" ON "gallery_items" USING btree ("niyam_id");--> statement-breakpoint
CREATE INDEX "idx_curricula_city" ON "curricula" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_curriculum_items_section" ON "curriculum_items" USING btree ("section_id");--> statement-breakpoint
CREATE INDEX "idx_curriculum_sections_curriculum" ON "curriculum_sections" USING btree ("curriculum_id");--> statement-breakpoint
CREATE INDEX "idx_progress_reports_student" ON "progress_reports" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_student_curriculum_progress_student" ON "student_curriculum_progress" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_student_curriculum_progress_item" ON "student_curriculum_progress" USING btree ("curriculum_item_id");--> statement-breakpoint
CREATE INDEX "idx_exam_answers_attempt" ON "exam_answers" USING btree ("attempt_id");--> statement-breakpoint
CREATE INDEX "idx_exam_attempts_exam" ON "exam_attempts" USING btree ("exam_id");--> statement-breakpoint
CREATE INDEX "idx_exam_attempts_student" ON "exam_attempts" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_exam_question_options_question" ON "exam_question_options" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "idx_exam_questions_exam" ON "exam_questions" USING btree ("exam_id");--> statement-breakpoint
CREATE INDEX "idx_online_exams_city" ON "online_exams" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_donation_campaigns_city" ON "donation_campaigns" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_donations_donor" ON "donations" USING btree ("donor_user_id");--> statement-breakpoint
CREATE INDEX "idx_donations_campaign" ON "donations" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "idx_donations_razorpay_order" ON "donations" USING btree ("razorpay_order_id");--> statement-breakpoint
CREATE INDEX "idx_homework_assignments_batch" ON "homework_assignments" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_homework_submissions_assignment" ON "homework_submissions" USING btree ("assignment_id");--> statement-breakpoint
CREATE INDEX "idx_homework_submissions_student" ON "homework_submissions" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_registration_form_configs_city" ON "registration_form_configs" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_registration_form_responses_config" ON "registration_form_responses" USING btree ("form_config_id");--> statement-breakpoint
CREATE INDEX "idx_registration_form_responses_user" ON "registration_form_responses" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_registration_form_responses_student" ON "registration_form_responses" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_service_request_messages_request" ON "service_request_messages" USING btree ("request_id");--> statement-breakpoint
CREATE INDEX "idx_service_requests_student" ON "service_requests" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_service_requests_assigned" ON "service_requests" USING btree ("assigned_to");--> statement-breakpoint
CREATE INDEX "idx_service_requests_parent" ON "service_requests" USING btree ("parent_user_id");--> statement-breakpoint
CREATE INDEX "idx_service_requests_centre" ON "service_requests" USING btree ("centre_id");--> statement-breakpoint
CREATE INDEX "idx_service_requests_city" ON "service_requests" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_created" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_audit_logs_actor" ON "audit_logs" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX "idx_competition_registrations_competition" ON "competition_registrations" USING btree ("competition_id");--> statement-breakpoint
CREATE INDEX "idx_competition_registrations_student" ON "competition_registrations" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_competitions_city" ON "competitions" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_push_quiz_attempts_push_quiz" ON "push_quiz_attempts" USING btree ("push_quiz_id");--> statement-breakpoint
CREATE INDEX "idx_push_quiz_attempts_student" ON "push_quiz_attempts" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_push_quiz_questions_push_quiz" ON "push_quiz_questions" USING btree ("push_quiz_id");--> statement-breakpoint
CREATE INDEX "idx_push_quizzes_batch" ON "push_quizzes" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_questions_city" ON "questions" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_quiz_attempts_event" ON "quiz_attempts" USING btree ("quiz_event_id");--> statement-breakpoint
CREATE INDEX "idx_quiz_attempts_student" ON "quiz_attempts" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_quiz_event_questions_event" ON "quiz_event_questions" USING btree ("quiz_event_id");--> statement-breakpoint
CREATE INDEX "idx_quiz_events_city" ON "quiz_events" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "idx_quiz_events_centre" ON "quiz_events" USING btree ("centre_id");--> statement-breakpoint
CREATE INDEX "idx_quiz_events_batch" ON "quiz_events" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_device_push_tokens_user" ON "device_push_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_enquiries_status" ON "enquiries" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_notifications_user" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_notifications_user_read" ON "notifications" USING btree ("user_id","read_at");