-- Step 5 — system_config table (key/value JSONB) + seed defaults for the
-- ten Step-5 configurable knobs (rate limits, TTLs, session caps, etc.).
--
-- Hand-written (not regenerated by drizzle-kit): the table is declared in
-- Drizzle's schema for type-safe reads, but the SQL here is canonical. Any
-- future column additions land in a new numbered migration, never by
-- re-running `pnpm db:generate`.
--
-- This table is consumed at runtime by `SystemConfigService` which caches
-- reads in Redis (60s) and falls through to env-var defaults when a key is
-- missing. Writes are super_admin-only (Step 5 — wired in the admin module
-- in Step 6+).

CREATE TABLE "system_config" (
  "key"        text PRIMARY KEY,
  "value"      jsonb NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by" uuid REFERENCES "users"("id") ON DELETE SET NULL
);--> statement-breakpoint

-- Seed the ten Step-5 keys with their inferred defaults. ON CONFLICT
-- DO NOTHING so re-running the migration after an admin edit is safe.
INSERT INTO "system_config" ("key", "value") VALUES
  ('otp.ttl_seconds',                to_jsonb(300)),
  ('otp.send.per_minute_per_phone',  to_jsonb(3)),
  ('otp.send.per_hour_per_phone',    to_jsonb(10)),
  ('otp.send.per_hour_per_ip',       to_jsonb(30)),
  ('otp.verify.max_attempts',        to_jsonb(3)),
  ('session.max_active_per_user',    to_jsonb(5)),
  ('jwt.access_ttl_seconds',         to_jsonb(900)),
  ('jwt.refresh_ttl_seconds',        to_jsonb(2592000)),
  ('impersonation.ttl_minutes',      to_jsonb(30)),
  ('student_view.min_age_years',     to_jsonb(13)),
  ('audit.async_enabled',            to_jsonb(false))
ON CONFLICT ("key") DO NOTHING;
